# Generated by Django 5.2.4 on 2025-07-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True, verbose_name="Announcement URL")),
                (
                    "reference",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Announcement Reference",
                    ),
                ),
                (
                    "department",
                    models.CharField(max_length=3, verbose_name="Department Code"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City Name")),
                (
                    "postal_code",
                    models.CharField(max_length=5, verbose_name="Postal Code"),
                ),
                (
                    "condominium_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Condominium Expenses",
                    ),
                ),
            ],
        ),
    ]
